### ISSUE TITLE
ImportError: No module named 'xpcom'

### ISSUE THREAD

**Issue by blakem17** [mjdorma/pyvbox#104]
##### ENVIRONMENT

- Operating System: Linux Mint 18.3
- Python version: 3.5
- VirtualBox version: 5.2
- VirtualBox SDK version: 5.2

- pyvbox version:
- [x ] Happens in latest `master` branch?

##### SUMMARY
Cannot initialize a new instance of virtualbox. This was working with Windows but is now failing on linux.

##### STEPS TO REPRODUCE
vbox = virtualbox.VirtualBox(

##### EXPECTED RESULTS
xpcom to run

##### ACTUAL RESULTS
thon3 SiteUpdater.py 
Traceback (most recent call last):
  File "SiteUpdater.py", line 1, in <module>
    from getInfo import *
  File "/media/blake/shared/PythonVBoxController/PythonVBoxController/getInfo.py", line 13, in <module>
    vbox = virtualbox.VirtualBox()
  File "/usr/local/lib/python3.5/dist-packages/virtualbox/library_ext/vbox.py", line 22, in __init__
    manager = virtualbox.Manager()
  File "/usr/local/lib/python3.5/dist-packages/virtualbox/__init__.py", line 137, in __init__
    self.manager = vboxapi.VirtualBoxManager(mtype, mparams)
  File "/usr/local/lib/python3.5/dist-packages/vboxapi/__init__.py", line 989, in __init__
    self.platform = PlatformXPCOM(dPlatformParams)
  File "/usr/local/lib/python3.5/dist-packages/vboxapi/__init__.py", line 750, in __init__
    import xpcom.vboxxpcom
ImportError: No module named 'xpcom'

**Comment by SethMichaelLarson** [comment]
Have you downloaded and installed the VirtualBox SDK from the virtualbox.org?
If you have, what steps did you take to install it?

**Comment by blakem17** [comment]
Figured it out. It was an issue with the VBOX SDK install
https://forums.virtualbox.org/viewtopic.php?f=7&t=47712

Downloaded and extracted the sdk.
Added the environment variables.
VBOX_INSTALL_PATH=/usr/lib/virtualbox
VBOX_SDK_PATH=/usr/lib/virtualbox/sdk //the directory were I extract the sdk :-)
PYTHONPATH=/usr/lib/virtualbox/sdk/bindings/xpcom/python

CD into the sdk/install directory
ran sudo python3 vboxapisetup.py install

Now the script is running fine.
Thanks for pointing me in the right direction, Feel free to close =D

**Comment by SethMichaelLarson** [comment]
I'm glad you were able to figure this out! :)
