### ISSUE TITLE
alter groups on an existing machine (IMachine)

### ISSUE THREAD

**Issue by jgander** [mjdorma/pyvbox#21]
Attempting to adjust the group for an already registered virtual machine, see example below:

import virtualbox
vbox = virtualbox.VirtualBox()
machine = vbox.find_machine('win7')
 -> <virtualbox.library_ext.machine.IMachine at 0x7f08108ed350>
machine.groups
 -> [u'/']
type(machine.groups)
 -> list

At ths point the list cannot be appended, replace, pop etc.

**Comment by SethMichaelLarson** [comment]
This is something I want to get into the next release.

**Comment by SethMichaelLarson** [comment]
So I just did a little inspection and the `.groups` method doesn't return a list any more? It returns a `str` value?

**Comment by SethMichaelLarson** [comment]
Seems like I'm correct that this is now a string value and is therefore editable. No helper needed! Closing this.
