### ISSUE TITLE
Pool machine creation hangs, session is not returned

### ISSUE THREAD

**Issue by ultramango** [mjdorma/pyvbox#25]
Virtual environment:
Linux machine (RedHat based), a new pool machine is being created (non existed before).

Test code (just a piece):
--- 8< ---
pool = virtualbox.pool.MachinePool("Some Linux Machine")
session = pool.acquire("john", "john1234", "gui")
--- 8< ---

Problem is that it will timeout on this operation and never return a session object, problem seem to be in:
guest.py -> IGuest -> create_session -> line: "session.file_query_info(test_file)" (test for "/bin/sh" file)

It keeps raising exception with error message something like: "object exists but it not a file", the problem is that "/bin/sh" is a link to "bash".

**Comment by SethMichaelLarson** [comment]
This is fixed in 1.0.0 of pyvbox.
