### ISSUE TITLE
safearray issue on windows with win32com

### ISSUE THREAD

**Issue by patricklx** [mjdorma/pyvbox#27]
I tried to use pyvbox, but had some issues with win32com complaining about safearrays. It seems it only accepts base types. So if Enums are passed it complains...
I edited the function [_set_attr](https://github.com/mjdorma/pyvbox/blob/master/virtualbox/library_base.py#L151) to check if value is an instance of enum and if it is i convert it to int.  Works so far on windows, i don't know if this affects linux systems

**Comment by SethMichaelLarson** [comment]
I think this bug no longer occurs in 1.0.0
