### ISSUE TITLE
Running on Mac OS X got Segmentation fault: 11

### ISSUE THREAD

**Issue by John-Lin** [mjdorma/pyvbox#32]
Hello, 
I used this module on OS X Yosemite in ipython after I typed `vbox = virtualbox.VirtualBox()` then got Segmentation fault: 11

Does someone encounter this problem? How to fix it?

Ubuntu has no this issue.

The detail message
$ ipython
Python 2.7.8 (default, Oct 18 2014, 00:36:49)
Type "copyright", "credits" or "license" for more information.

IPython 2.3.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import virtualbox

In [2]: vbox = virtualbox.VirtualBox()
Segmentation fault: 11

**Comment by chirayuk** [comment]
I'm also seeing a segmentation fault with vanilla python 2.7 (installed from macports) and pyvbox installed via pip.  `VBoxManage --version` gives `4.3.20r96996`.

```
Thu 12:18:20 2015-01-22 @cheshire:~ % python -c "import virtualbox; virtualbox.VirtualBox()"
[1]    25978 segmentation fault  python -c "import virtualbox; virtualbox.VirtualBox()"
```

**Comment by kwilczynski** [comment]
I just stumbled into the same issue. I'd love to figure out how to fix this on Darwin / OS X.

**Comment by chirayuk** [comment]
Afaik, you **have** to use the system python for this to work.  You can't use a MacPorts or other 3rd party installed version—it's not compatible.

**Comment by mjdorma** [comment]
Thanks @chirayuk, you are 100% correct.  I have never tried running this from anything other then the system installed python.
