### ISSUE TITLE
Unable to import appliance!

### ISSUE THREAD

**Issue by hosseinkhani** [mjdorma/pyvbox#33]
Im new to pyvbox
I tried to import an ovf file but get this error
virtualbox.library.OleErrorFail: 0x80004005 (Cannot interpret appliance without reading it first (call read() before interpret()))

this is the code
>>> import virtualbox
>>> vbox = virtualbox.VirtualBox()
>>> apl = vbox.create_appliance()
>>> apl.read('~/Documents/ubuntu.ova')

why before reading completion , interpret is called!

**Comment by markhuber** [comment]
I've found that the underlying virtualbox api that pyvbox relies on is extremely temperamental about the path to the file. I suggest running the path through os.path.absdir() and strip() . Even stray characters after os.path.absdir will cause this error.

**Comment by mjdorma** [comment]
@markhuber I agree.  The tilde may be the cause of the issue in the posted example. Cheers

**Comment by XayOn** [comment]
This is reaaally old, but just to clarify in case anyone comes to this bugreport:

.read('~/Documents/ubuntu.ova') will not find the file (as it really does not exist), therefore the error.
What you really whated to do is api.read(os.path.expanduser('~/Documents/ubuntu.ova').
