### ISSUE TITLE
Failed to find attribute videoCaptureFile 

### ISSUE THREAD

**Issue by amazpyel** [mjdorma/pyvbox#38]
I tried to run example of capturing video (https://gist.github.com/mjdorma/9045317) and got the following error:
```
Traceback (most recent call last):
  File "capture_video.py", line 13, in <module>
    session.machine.video_capture_file = os.path.abspath("test.webm")
  File "/usr/local/lib/python2.7/dist-packages/pyvbox-0.2.2-py2.7.egg/virtualbox/library.py", line 9049, in video_capture_file
    return self._set_attr("videoCaptureFile", value)
  File "/usr/local/lib/python2.7/dist-packages/pyvbox-0.2.2-py2.7.egg/virtualbox/library_base.py", line 163, in _set_attr
    attr = self._search_attr(name, prefix='set')
  File "/usr/local/lib/python2.7/dist-packages/pyvbox-0.2.2-py2.7.egg/virtualbox/library_base.py", line 152, in _search_attr
    raise AttributeError("Failed to find attribute %s in %s" % (name, self))
AttributeError: Failed to find attribute videoCaptureFile in Windows 7
```
I just renamed **win7** to **Windows 7** .

**Environment:**
-Python 2.7.3
-Ubuntu 12.04.5 
-pyvbox-0.2.2
-Virtual Box 4.1.18r78361

**Comment by mjdorma** [comment]
Hi,

Maybe this attribute didn't exist in VirtualBox 4.1?  The API was generated against the last 4.3x release.

You have just reminded me that I need to start moving to get 5.x API compatibility (this will be a compatibility breaking change). 

Thanks,
Mick

**Comment by amazpyel** [comment]
Hi @mjdorma,

Virtual Box updated (Oracle VM VirtualBox Manager 4.3.30 ) and video capturing feature appeared from Virtual Box UI controls but same error is still present. :(

Thank you,
Alex

**Comment by mjdorma** [comment]
Hi,

Thanks for pointing this out.  I just had a look and I think this commit solves your issue.  If you patched this over your current install does it resolve your issue?  3188c7472470b64a70d69bc44b186068c0ed59c1

If it does I might backport it from this 1.0.0 branch to a 0.2.3 release. 

Cheers

**Comment by mjdorma** [comment]
I just cherry picked that 1.0.0 commit back to master.  Hopefully that will resolve your issue.

**Comment by amazpyel** [comment]
Thank you, Mick!

It works as expected.
