### ISSUE TITLE
Vboxapi module not found

### ISSUE THREAD

**Issue by vnpraveendesu** [mjdorma/pyvbox#43]
Hi 
    Last week, I have installed  pyvbox on my ubuntu machine. Whenever import the virtualbox module, throws an error vboxapi module not found. I tried to intsall the package using pip(pip install vboxapi).
"Could not find a version that satisfies the requirement vboxapi (from versions)"
Please let me know, How can i install the vboxapi package using pip.

**Comment by SethMichaelLarson** [comment]
Try downloading the VirtualBox SDK from the website. That's where the vboxapi module is distributed from.
