### ISSUE TITLE
GuestSession failed to start

### ISSUE THREAD

**Issue by aGGeRReS** [mjdorma/pyvbox#47]
python 2.7.6
pyvbox 1.0.0
Host OS - Ubuntu 14.04
Guest OS - Windows7, x32
VirtualBox 5.0.16

Hello. I am trying to run program on the guest OS. This is what I do:

```
vbox = virtualbox.VirtualBox()
session = virtualbox.Session()
vm = vbox.find_machine('Windows7')
vm.launch_vm_process(session, 'gui', '').wait_for_completion()

session = vm.create_session()
time.sleep(35)
gs = session.console.guest.create_session('win7', '')
process, stdout, stderr = gs.execute('C:\\Windows\\System32\\cmd.exe', ['/C', 'tasklist'])
print stdout
```

VM starts normally, but then:

> File "runonguest.py", line 39, in <module>
>     gs = session.console.guest.create_session('win7', '')
>   File "/usr/local/lib/python2.7/dist-packages/virtualbox/library_ext/guest.py", line 24, in create_session
>     raise SystemError("GuestSession failed to start")
> SystemError: GuestSession failed to start

What I am doing wrong?
Thank you.

**Comment by aGGeRReS** [comment]
So far I managed to launch program on the guest OS in VirtualBox. The solution based on the (undocumented as I see) fact that VBox API just doesn't launch session in case user account has no password. So I created new user account with password on guest's Windows7.

So what you can do is:

    In [15]: gs = session.console.guest.create_session('user', 'user')

    In [16]: process, stdout, stderr = gs.execute('C:\\Windows\\System32\\cmd.exe', ['/C', 'tasklist'])

    In [17]: print stdout

    Image Name                     PID Session Name        Session#    Mem Usage
    ========================= ======== ================ =========== ============
    System Idle Process              0 Services                   0         12 K
    System                           4 Services                   0        528 K
    smss.exe                       264 Services                   0        688 K
    csrss.exe                      340 Services                   0      2,824 K
    wininit.exe                    388 Services                   0      3,128 K
    csrss.exe                      400                            1      3,572 K
    winlogon.exe                   440                            1      5,556 K 
.....

After I tried using native VirtualBox API through Linux console, and it is also a need for password:

VBoxManage guestcontrol "Windows7" --verbose  --username user --password user run --exe "C:\\
Windows\\System32\\cmd.exe" -- cmd.exe /c tasklist

Image Name                     PID Session Name        Session#    Mem Usage
========================= ======== ================ =========== ============
System Idle Process              0 Services                   0         12 K
System                           4 Services                   0        532 K
smss.exe                       264 Services                   0        688 K
csrss.exe                      340 Services                   0      2,848 K
wininit.exe                    388 Services                   0      3,128 K
csrss.exe                      400                            1      3,572 K
winlogon.exe                   440                            1      5,556 K
......

**Comment by SethMichaelLarson** [comment]
Thank you for this issue! This should be documented somewhere, perhaps inside of `guest.create_session()`

**Comment by SethMichaelLarson** [comment]
This issue has been reported in #62. Thank you @aGGeRReS!
