### ISSUE TITLE
restoreSnapshot trouble

### ISSUE THREAD

**Issue by alanr917** [mjdorma/pyvbox#49]
Hi, I'm having a hard time restoring a machine from a snapshot. This is one of the many things that I've tried, and this has gotten me the closest:

`import virtualbox

vm = virtualbox.VirtualBox().find_machine('test')
vm.restoreSnapshot()`

but then I get the error: `AttributeError: 'IMachine' object has no attribute 'restoreSnapshot'`

and by reading this page on the documentation (https://www.virtualbox.org/sdkref/interface_i_machine.html#a5b696740ceccb14750718e2648d6928c) it seems as though iMachine _does_ have an attribute of restoreSnapshot. Any ideas?

**Comment by SethMichaelLarson** [comment]
You can't use it directly on a machine, you have to use it from a session.
Check out MachinePool in `pool.py` for an example.
