### ISSUE TITLE
Failed to create clone

### ISSUE THREAD

**Issue by alanr917** [mjdorma/pyvbox#50]
Hello everyone, I am having troubles launching a VM. When I try to start the VM like this: 
`import virtualbox
vm = virtualbox.VirtualBox().find_machine('test')
session = vm.create_session()
s = virtualbox.Session()
vm.launch_vm_process()`

I get an error saying `(The machine 'test' is already locked by a session (or being locked or unlocked))
`

When I try to unlock the machine, it says that it's not locked.

But then when I try to lock it, using this command: `vm.create_session(lock_type=virtualbox.library.LockType.write)`

I get the following error: `Failed to create clone - 0x80bb0007 (The machine 'test' is already locked for a session (or being unlocked))`

Can anyone help me with this?

Thanks!

**Comment by SethMichaelLarson** [comment]
Looks like you're creating two separate sessions, `create_session()` locks the returned session already. Instead of calling `create_session()` try calling `launch_vm_process()` on an empty session object.
