### ISSUE TITLE
Win32 exception occurred releasing IUnknown at 0x20656b10

### ISSUE THREAD

**Issue by dickreuter** [mjdorma/pyvbox#52]
import virtualbox
vbox = virtualbox.VirtualBox()
print("VM(s):\n + %s" % "\n + ".join([vm.name for vm in vbox.machines]))
session = virtualbox.Session()

output:
Win32 exception occurred releasing IUnknown at 0x20656b10

**Comment by SethMichaelLarson** [comment]
I'd like to do some additional exploration into this. I have a feeling it has to do with Windows `COM` usage.
If you have any more information you want to add to this @dickreuter it would be greatly appreciated. :)

**Comment by SethMichaelLarson** [comment]
I haven't heard much on this issue lately, if you have more information please add it here and I'll reopen.
