### ISSUE TITLE
Remove machine not working

### ISSUE THREAD

**Issue by ja9749** [mjdorma/pyvbox#53]
This is in python 3.5.2

code:

```
import virtualbox

vbox = virtualbox.VirtualBox()
vm = vbox.find_machine(<name of your machine>)
vm.remove(delete=True)
```

output:

>  if self.state >= library.MachineState.running:
> TypeError: unorderable types: MachineState() >= MachineState()

**Comment by SethMichaelLarson** [comment]
Might need to add `__gt__()`, `__lt__()`, etc... commands to the `Enum` type. I don't know why it wouldn't try to use `__cmp__()` though.

**Comment by SethMichaelLarson** [comment]
So I'm almost positive this is fixed. If not just ping this issue @ja9749.
