### ISSUE TITLE
unable to create full machine clone

### ISSUE THREAD

**Issue by choman** [mjdorma/pyvbox#55]
Sorry if i'm missing this.  But using the API below I'm able to create what I think are linked clones
   
  self.clone = virtualbox.library.IMachine.clone(self.BASE,
                                        mode=self.CLONE_MODE,
                                        groups=["/pool"],
                                        basefolder=self.data_dir)

CLONE_MODE is (1) or machine_state.   

What mode/option combo creates a full machine clone.  I can seem to find it

**Comment by SethMichaelLarson** [comment]
Take a look in the `MachinePool` implementation. I found this extremely useful for cloning machines.

**Comment by choman** [comment]
So I'm looking for a bit more than what the current support of MachinePool provides,  for example 
I'd like the pool to be created in a different directory (RAID filesystem).  Also the ability to do full 
machine clones as well as linked clones. So I was kinda writing my own with the libraries at hand.  Although I do like the speed that MachinePool creates the clones.  When I get done I should have a nice 
VDI implementation. In case you're curious: https://github.com/choman/vboxvdi

A couple other issues I have is the IMachine.clone groups seems to only work on the filesystem and 
not in the Vbox GUI

But I did try it, but it throws a shoe

pool = virtualbox.pool.MachinePool(self.BASE)
sessions = []
for i in range(3):
    sessions.append(pool.acquire("choman", "abcd1234"))

Traceback (most recent call last):
  File "./vboxvdi2", line 593, in <module>
Session afb01743-0262-4463-b57b-56eb570e7bc5 state changed: Unlocked
    a = vboxvdi()
  File "./vboxvdi2", line 141, in __init__
    self.createpool()
  File "./vboxvdi2", line 205, in createpool
    sessions.append(pool.acquire("choman", "abcd1234"))
  File "/usr/local/lib/python2.7/dist-packages/pyvbox-1.0.0-py2.7.egg/virtualbox/pool.py", line 165, in acquire
    act = console.get_device_activity(DeviceType.hard_disk)
  File "/usr/local/lib/python2.7/dist-packages/pyvbox-1.0.0-py2.7.egg/virtualbox/library.py", line 13884, in get_device_activity
    raise TypeError("type_p can only be an instance of type list")
TypeError: type_p can only be an instance of type list
Unregistering <virtualbox.library.IEventListener object at 0x7f6e74896510> due to VBoxError on get_event
Failed to unregister listener <virtualbox.library.IEventListener object at 0x7f6e74896510>
Unregistering <virtualbox.library.IEventListener object at 0x7f6e7edf3390> due to VBoxError on get_eventUnregistering <virtualbox.library.IEventListener object at 0x7f6e74896750> due to VBoxError on get_eventUnregistering <virtualbox.library.IEventListener object at 0x7f6e74896090> due to VBoxError on get_eventUnregistering <virtualbox.library.IEventListener object at 0x7f6e748962d0> due to VBoxError on get_event
Failed to unregister listener <virtualbox.library.IEventListener object at 0x7f6e748962d0>


Failed to unregister listener <virtualbox.library.IEventListener object at 0x7f6e74896090>Failed to unregister listener <virtualbox.library.IEventListener object at 0x7f6e74896750>Failed to unregister listener <virtualbox.library.IEventListener object at 0x7f6e7edf3390>

**Comment by SethMichaelLarson** [comment]
I'll take a look at this more when at home, I've also had to implement my own MachinePool for projects.

**Comment by choman** [comment]
another thing I was looking for was the launching of the sessions without
an accout.  so I have
idle machines awaiting users to access, more vdi like



Together We Win!   Looking for cloud storage, try pCloud
<https://my.pcloud.com/#page=register&invite=O7KbZIt0T67> (10g free
<https://my.pcloud.com/#page=register&invite=O7KbZIt0T67>)
--
Chad

Some people, when confronted with a problem, think "I know, I'll use
Windows."
Now they have two problems.

Some people claim if you play a Windows Install Disc backwards you'll hear
satanic Messages.
That's nothing, if you play it forward it installs Windows

**Comment by SethMichaelLarson** [comment]
You need an account to launch a `IGuestSession` because it relies on the Guest Additions being installed which requires a username and password. Don't think auth-less logins are going to be a part of the VirtualBox API.

**Comment by SethMichaelLarson** [comment]
Okay so I think I figured out the original issue. Take a look at [`IMachine.clone()`](https://github.com/mjdorma/pyvbox/blob/master/virtualbox/library_ext/machine.py#L64), specifically the `options` argument. By default it creates a linked clone, by using an empty `options=[]` parameter it shouldn't link the clones together.
