### ISSUE TITLE
Problem creating medium

### ISSUE THREAD

**Issue by gabriel-chiele** [mjdorma/pyvbox#59]
When tried to create a medium using:

```
vbox = virtualbox.VirtualBox()

bus = virtualbox.library.StorageBus(2)

vm.add_storage_controller("SATA", bus)

access_mode = virtualbox.library.AccessMode(2)

device_type = virtualbox.library.DeviceType(3)

medium = vbox.create_medium("VDI", vm_hd_path, access_mode, device_type)

medium.create_base_storage()

medium = vbox.open_medium(vm_hd_path, device_type, access_mode, True)

vm.attach_device(vm_hd_name, 0, 0, device_type, medium)
```

I got the following error:

Traceback (most recent call last):
  File "environment_configuration.py", line 268, in <module>
    enviroment.method()
  File "environment_configuration.py", line 211, in method
    medium = vbox.create_medium("VDI", vm_hd_path, access_mode, device_type)
  File "/usr/local/lib/python2.7/dist-packages/virtualbox/library.py", line 7289, in create_medium
    in_p=[format_p, location, access_mode, a_device_type_type])
  File "/usr/local/lib/python2.7/dist-packages/virtualbox/library_base.py", line 170, in _call
    method = self._search_attr(name)
  File "/usr/local/lib/python2.7/dist-packages/virtualbox/library_base.py", line 151, in _search_attr
    raise AttributeError("Failed to find attribute %s in %s" % (name, self))
AttributeError: Failed to find attribute createMedium in <virtualbox.library_ext.vbox.IVirtualBox object at 0x7f03459e5650>

**Comment by SethMichaelLarson** [comment]
What version of the VirtualBox SDK do you have installed?

**Comment by gabriel-chiele** [comment]
The virtualbox installed on my machine is 4.3.36_Ubuntur105129

**Comment by SethMichaelLarson** [comment]
That's quite an old version, what version of `pyvbox` package are you running?

**Comment by SethMichaelLarson** [comment]
I'm guessing you're using a recent version of `pyvbox`?

I did some research, for VirtualBox 4.3.x instead of being named `create_medium` the function was called [`create_hard_disk()`](https://github.com/mjdorma/pyvbox/blob/25f5f92fe1ced119aa4b7d1567fdd512629cb1b0/virtualbox/library.py#L6581)
I suggest downloading and installing an older version of the `pyvbox` package so that you can get proper advertised support for the 4.3.x VirtualBox SDK.

**Comment by gabriel-chiele** [comment]
I downgraded the library to 0.2.2, and now i can't open medium.

Now the code:

 ```
            access_mode = virtualbox.library.AccessMode(2)

            device_type = virtualbox.library.DeviceType(3)

            hd = vbox.create_hard_disk("VDI", vm_hd_path)

            progress = hd.create_base_storage(20000, [virtualbox.library.MediumVariant(0)])

            medium = vbox.open_medium(hd.location, device_type, access_mode, True)

            vm.attach_device(vm_hd_name, 0, 0, device_type, medium)

```

present the error:

Traceback (most recent call last):
  File "environment_configuration.py", line 221, in <module>
    enviroment.method()
  File "environment_configuration.py", line 156, in method
    medium = vbox.open_medium(hd.location, device_type, access_mode, True)
  File "/usr/local/lib/python2.7/dist-packages/virtualbox/library.py", line 6735, in open_medium
    in_p=[location, device_type, access_mode, force_new_uuid])
  File "/usr/local/lib/python2.7/dist-packages/virtualbox/library_base.py", line 173, in _call
    return self._call_method(method, in_p=in_p)
  File "/usr/local/lib/python2.7/dist-packages/virtualbox/library_base.py", line 199, in _call_method
    raise errobj
virtualbox.library.VBoxErrorObjectNotFound: 0x80bb0001 (Object corresponding to the supplied arguments does not exist (VBOX_E_OBJECT_NOT_FOUND))

**Comment by SethMichaelLarson** [comment]
Did you wait for the `progress` object to complete successfully?

**Comment by gabriel-chiele** [comment]
yes, it return True when tested if progess.completed

**Comment by SethMichaelLarson** [comment]
And still you receive the same error when your try to open the medium after waiting for the progress to complete?

**Comment by gabriel-chiele** [comment]
Yes, the error persist, even if i wait.

```
progess = medium.create_base_storage(20000, [virtualbox.library.MediumVariant(0)])
while not progess.completed == True:
    print "not ready yet"
medium = vbox.open_medium(medium.location, device_type, access_mode, True)
```

**Comment by SethMichaelLarson** [comment]
Could you try using `progress.wait_for_completion()` as well?

**Comment by gabriel-chiele** [comment]
Same result.

**Comment by SethMichaelLarson** [comment]
What's the value of `medium.location` after calling `medium.create_base_storage()`?

**Comment by gabriel-chiele** [comment]
It contains the path: /home/environment_config/virtual_box/HD.vdi

**Comment by SethMichaelLarson** [comment]
Could you try using the names of the `enum` types (eg `virtualbox.library.AccessMode.ReadWrite` and `virtualbox.library.DeviceType.hard_disk`)? Usually this error is thrown when you pass something the SDK doesn't understand into a function call.

**Comment by gabriel-chiele** [comment]
I made the modification, but the error still happens.
```
access_mode = virtualbox.library.AccessMode.read_write
device_type = virtualbox.library.DeviceType.hard_disk
hd = vbox.create_hard_disk("VDI", vm_hd_path)
progress = hd.create_base_storage(20000, [virtualbox.library.MediumVariant(0)])
progress.wait_for_completion(-1)
medium = vbox.open_medium(hd.location, device_type, access_mode, True)
vm.attach_device(vm_hd_name, 0, 0, device_type, medium)
```

**Comment by SethMichaelLarson** [comment]
Can you check that the `hd.state` is equal to `MediumState.created` after you call `hd.create_base_storage()`?

**Comment by gabriel-chiele** [comment]
When i try to access the state of hd an error happen.

Traceback (most recent call last):
  File "environment_configuration.py", line 221, in <module>
    enviroment.method()
  File "environment_configuration.py", line 154, in method
    if hd.state == virtualbox.library.MediumState.created:
  File "/usr/local/lib/python2.7/dist-packages/virtualbox/library.py", line 18700, in state
    ret = self._get_attr("state")
  File "/usr/local/lib/python2.7/dist-packages/virtualbox/library_base.py", line 156, in _get_attr
    attr = self._search_attr(name, prefix='get')
  File "/usr/local/lib/python2.7/dist-packages/virtualbox/library_base.py", line 152, in _search_attr
    raise AttributeError("Failed to find attribute %s in %s" % (name, self))
AttributeError: Failed to find attribute state in <virtualbox.library.IMedium object at 0x7f2ee9d53190>

**Comment by SethMichaelLarson** [comment]
That makes me wonder if that `Medium` object is actually getting created or not... hm... I'll try to reproduce this this upcoming weekend and I'll get back to you. Thanks for hanging in there and providing all this information.

**Comment by SethMichaelLarson** [comment]
This is next on my list of debugging. If possible it would be great if you could see if this also occurs with VirtualBox 5.1.x and the latest pyvbox.

**Comment by gabriel-chiele** [comment]
I tested with virtual box 5.1.22 and pyvbox 1.0.0 and the problema persists.

  File "test.py", line 171, in method()
    medium = vbox.open_medium(hd.location, device_type, access_mode, True)      
  File "/usr/local/lib/python2.7/dist-packages/virtualbox/library.py", line 7391, in open_medium
    in_p=[location, device_type, access_mode, force_new_uuid])
  File "/usr/local/lib/python2.7/dist-packages/virtualbox/library_base.py", line 172, in _call
    return self._call_method(method, in_p=in_p)
  File "/usr/local/lib/python2.7/dist-packages/virtualbox/library_base.py", line 198, in _call_method
    raise errobj
virtualbox.library.VBoxErrorObjectNotFound: 0x80bb0001 (Object corresponding to the supplied arguments does not exist (VBOX_E_OBJECT_NOT_FOUND))

**Comment by SethMichaelLarson** [comment]
Thank you very much for all the help with this issue!

**Comment by SethMichaelLarson** [comment]
Okay so I've figured this out a bit more, it seems that VDI doesn't like the size it's being passed. To see the error properly you have to do this:

```
access_mode = virtualbox.library.AccessMode.read_write
device_type = virtualbox.library.DeviceType.hard_disk
hd = vbox.create_hard_disk("VDI", vm_hd_path)
progress = hd.create_base_storage(20000, [virtualbox.library.MediumVariant(0)])
progress.wait_for_completion(-1)
print(progress.error_info.text)
# Could not create the medium storage unit 'C:\\Users\\sethm\\Desktop\testme.vdi'.\nVD: The given disk size 2000 is not aligned on a sector boundary (512 bytes) (VERR_VD_INVALID_SIZE)
```

**Comment by SethMichaelLarson** [comment]
Yep that was it, you have to check the `progress.result_code`, it should be zero. If it's not zero you should check out `progress.error_info.text` for information why it's not working.
It seems that there's a minimum size (1 GB worked for me) and it has to be a multiple of your sector size (512 in my case).

Thanks for this report!
