### ISSUE TITLE
Is this package licensed under MIT or Apache-2.0?

### ISSUE THREAD

**Issue by SethMichaelLarson** [mjdorma/pyvbox#61]
Just noticed this difference while looking at `setup.py`. Within `setup.py` it seems that the package is licensed under `Apache-2.0` but looking at the contents of `LICENSE` it shows that the package is licensed under `MIT`.

Which of these is correct? When that's determined the other should be fixed.
cc: @mjdorma

**Comment by mjdorma** [comment]
Wow, good spot!  I'm happy to go with MIT all the way.  If you have a counter recommendation I'd be happy to take that onboard too?

**Comment by SethMichaelLarson** [comment]
I would actually recommend Apache-2.0. It's MIT with an additional provision to protect against malicious patent stuff. It's a more modern take on liberal open source licensing.

**Comment by mjdorma** [comment]
Great! Let's go apache-2.0 👍  (I'm a licensing noob).

**Comment by SethMichaelLarson** [comment]
You can read here about Apache-2.0. I know as much about licensing as this page knows about licensing. :P I'll send a PR fixing up `LICENSE`.
