### ISSUE TITLE
Move CHANGELOG to project root

### ISSUE THREAD

**Issue by SethMichaelLarson** [mjdorma/pyvbox#65]
There's no change log that shows the history of the module. Would be a good idea to start tracking changes now that we're 1.0.0.

**Comment by mjdorma** [comment]
There is this file used in the doc: docs/source/changelog.rst

Maybe this file can be moved ../../CHANGELOG and changeling.rst could simply .. include:: ../../CHANGELOG

**Comment by SethMichaelLarson** [comment]
Oh! I didn't even know it existed! I'll do what you suggest so it has a more prominent location. :)
