### ISSUE TITLE
Switch to using the enum module for Enumeration types

### ISSUE THREAD

**Issue by SethMichaelLarson** [mjdorma/pyvbox#86]
Also would greatly help with auto-complete for IDEs.
Place the descriptions for each value within the docstring of the enum.

**Comment by SethMichaelLarson** [comment]
Would require the use of `enum34` for Python 3.3 or earlier. We plan on supporting Python 2.7 for a while even into 2.0.0

**Comment by SethMichaelLarson** [comment]
Primarily we would use the `enum.IntEnum` as all our enumerations are integers.

**Comment by SethMichaelLarson** [comment]
One of the down-sides of switching to Python Enums is we lose our easy way to do docstrings, there has to be a way to use them with Python enums though. Will do some research on this.

**Comment by mjdorma** [comment]
I'm happy to take advice on this one.  Evolution is important ;).

**Comment by SethMichaelLarson** [comment]
This has been completed in the 2.0.0 branch
