### ISSUE TITLE
gs.execute() command with keys/params problems with space between command and keys!

### ISSUE THREAD

**Issue by angryjk** [mjdorma/pyvbox#96]
##### ENVIRONMENT

- Operating System: Ubuntu 16.04
- Python version: 2.7.7
- VirtualBox version: 5.1.24
- VirtualBox SDK version:....
- Location where VirtualBox SDK is installed: 
- pyvbox version: 1.4
- [x] Happens in latest `master` branch?

##### SUMMARY

When i am trying to execute command like gs.execute("ipconfig --help") throws error
the problem is in space between command and key of command 

##### STEPS TO REPRODUCE

 gs.execute("ipconfig --help")
##### EXPECTED RESULTS

understand how to pass command of win shell with params

##### ACTUAL RESULTS

just throws error that command not found

**Comment by SethMichaelLarson** [comment]
Have you tried `gs.execute(['ipconfig', '--help'])`?

**Comment by angryjk** [comment]
thanks, it works

**Comment by SethMichaelLarson** [comment]
Agreed! Are you confident in submitting a Pull Request?

**Comment by angryjk** [comment]
still have issues with another commands like gs.execute(['whoami','/?']) still question in that space! also Michael look on such commands as net share. After that ,if i am not right, will make a pull request

**Comment by SethMichaelLarson** [comment]
Try running `gs.execute('whoami', ['/?'])`? I've really got to rewrite the API for `.execute()` in 2.0.0

**Comment by angryjk** [comment]
aha, so i need to wrap only keys?

**Comment by SethMichaelLarson** [comment]
I believe so from looking at the API? Yeah that function definitely needs to be changed in 2.0.0 to match `subprocess.Popen` API.

**Comment by angryjk** [comment]
I have confused you! Do not change anything! It seems everything works, my fault

**Comment by angryjk** [comment]
making futher tests

**Comment by SethMichaelLarson** [comment]
Oh, it'd be great if you could post the code you got to work along with the output.

**Comment by angryjk** [comment]
it was your variant! gs.execute(["whoami","/?"]) without spaces

**Comment by SethMichaelLarson** [comment]
That's great to hear! I'm glad everything worked out. Is it safe to close this issue?

**Comment by angryjk** [comment]
defenitly yes! even "net share" is working fine!!! the problem was in my side! =(

**Comment by SethMichaelLarson** [comment]
Thanks for helping me help you work through this issue. We'd love to have you stick around and keep using the project. Good luck!
